version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    image: own_jenkins
    container_name: own_jenkins
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    volumes:
      - jenkins-volume:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - eval_6_networks

  postgres:
    image: postgres:13
    container_name: artifactory_postgres
    environment:
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artifactory
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eval_6_networks

  jfrog_artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.5
    ports:
      - 8081:8081
      - 8082:8082
    container_name: jfrog_artifactory
    environment:
      - JAVA_OPTIONS=-Dartifactory.jdbc.driver=org.postgresql.Driver -Dartifactory.jdbc.url=jdbc:postgresql://artifactory_postgres:5432/artifactory -Dartifactory.jdbc.user=artifactory -Dartifactory.jdbc.password=password
    depends_on:
      - postgres
    volumes:
      - jfrog-volume:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - eval_6_networks

networks:
  eval_6_networks: {}

volumes:
  jenkins-volume: {}
  jenkins-docker-certs: {}
  jfrog-volume: {}
  pgdata: {}
