pipeline {
    agent any

    tools {
        // Instalar Maven desde las herramientas globales de Jenkins
        maven 'Maven 3.6.3'
        jdk 'jdk-11'
        jfrog 'jfrog-cli'
    }

    environment {
        ARTIFACTORY_URL = 'http://jfrog_artifactory:8082/artifactory'
        ARTIFACTORY_REPO = 'retailoff-dev'
        ARTIFACTORY_CREDS = credentials('artifact-creds') // ID de las credenciales de Artifactory en Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Clonar el código fuente desde el repositorio
                git url: 'https://github.com/Wildesdar37/retail-off.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                // Cambiar al directorio retailoff antes de ejecutar comandos
                dir('retailoff') {
                    // Limpiar y construir el proyecto Maven
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                // Cambiar al directorio retailoff antes de ejecutar comandos
                dir('retailoff') {
                    // Ejecutar los tests del proyecto Maven
                    sh 'mvn test'
                }
            }
        }

        stage('Testing') {
            steps {
                dir('retailoff') {
                    // Show the installed version of JFrog CLI.
                    jf '-v'

                    // Show the configured JFrog Platform instances.
                    jf 'c show'

                    // Ping Artifactory.
                    jf 'rt ping'

                    // Create a file and upload it to a repository  in Artifactory
                    jf "rt u target/retailoff-0.0.1-SNAPSHOT.jar retailoff/${BUILD_TAG}/"

                    // Publish the build-info to Artifactory.
                    jf 'rt bp'
                }
            }
        }
    }

    post {
        success {
            echo 'Build and tests were successful!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}
